[project]
name = "FlashGBX"
version = "5.0.1"
description = "Reads and writes Game Boy and Game Boy Advance cartridge data"
readme = "README.md"
requires-python = ">=3.14"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]

authors = [
    { name = "Lesserkuma" }
]

dependencies = [
    "pyserial>=3.5",
    "Pillow>=10.0",
    "requests",
    "python-dateutil",
    "packaging",
    "PySide6>=6.11.2",
    "loguru>=0.7.3",
]

# Classifiers **hier unter project**, nicht scripts**
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: X11 Applications :: Qt",
    "Topic :: Terminals :: Serial",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Developers"
]

[project.urls]
Source = "https://github.com/Lesserkuma/FlashGBX/"
Tracker = "https://github.com/Lesserkuma/FlashGBX/issues"

[project.scripts]
flashgbx = "FlashGBX.FlashGBX:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["FlashGBX*"]

[tool.setuptools.package-data]
FlashGBX = ["res/**/*", "locale/**/*"]

[dependency-groups]
dev = [
    "pre-commit>=4.3",
    "pytest>=8.4",
    "pyright>=1.1.411",
    "ruff>=0.16.4",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
addopts = "-ra --strict-markers"
testpaths = ["tests"]

[tool.coverage.run]
branch = true
omit = [
    "FlashGBX/hw_GameBub.py",
    "FlashGBX/hw_GBFlash.py",
    "FlashGBX/hw_JoeyJr.py",
]
source = [
    "FlashGBX.DumpReport",
    "FlashGBX.CartridgeTypes",
    "FlashGBX.Flashcart",
    "FlashGBX.Formatter",
    "FlashGBX.GBMemory",
    "FlashGBX.IniSettings",
    "FlashGBX.InteractiveConsole",
    "FlashGBX.InteractiveConsoleWindow",
    "FlashGBX.i18n",
    "FlashGBX.Mapper",
    "FlashGBX.PocketCamera",
    "FlashGBX.PocketCameraWindow",
    "FlashGBX.Progress",
    "FlashGBX.RomFileAGB",
    "FlashGBX.RomFileDMG",
    "FlashGBX.hw_GBxCartRW",
    "FlashGBX.app",
]

[tool.coverage.report]
fail_under = 35
show_missing = true
skip_covered = true

[tool.pyright]
include = ["FlashGBX"]
exclude = [
    "FlashGBX/hw_GameBub.py",
    "FlashGBX/hw_GBFlash.py",
    "FlashGBX/hw_JoeyJr.py",
]
typeCheckingMode = "standard"
pythonVersion = "3.14"

[tool.ruff]
target-version = "py314"
line-length = 121
force-exclude = true
exclude = [
    "FlashGBX/hw_GameBub.py",
    "FlashGBX/hw_GBFlash.py",
    "FlashGBX/hw_JoeyJr.py",
]

[tool.ruff.lint]
# Add rule codes you want to ignore
select =["ALL"]
ignore = [
    "BLE001", # Do not catch blind exceoption
    "COM812", # Conflicts with the formatter
    "D203", # Conflicts with D211
    "D213", # Conflicts with D212
    "D102", #undocumented-public-method
    "N802", #invalid-function-name
    "PLR2004", #magic-value-comparison
    "T201", #print
    "ANN001", #missing-type-function-argument
    "ANN201", #missing-return-type-undocumented-public-function
    "S101", #assert
    "E501", #line-too-long
    "RUF001", #ambiguous-unicode-character-string
    "N806", #on-lowercase-variable-in-function
    "ERA001", #commented-out-codes
    "FBT002", #boolean-default-value-positional-argument
    "D103", #undocumented-public-function
    "C901", #complex-structure
    "D101", #undocumented-public-class
    "SLF001", #private-member-access
    "PLR0915", #too-many-statements
    "PLR0912", #too-many-branches
    "FBT001", #boolean-type-hint-positional-argument
    "TRY003", #raise-vanilla-args
    "F405", #undefined-local-with-import-star-usage
    "N803", #invalid-argument-name
    "ARG002", #unused-method-argument
    "D107", #undocumented-public-init
    "CPY001", #missing-copyright-notice
    "PLR0911", #too-many-return-statements
    "FBT003", #boolean-positional-value-in-call
    "ANN204", #missing-return-type-special-method
    "D100", #undocumented-public-module
    "PLC0415", #import-outside-top-level
    "S324", #hashlib-insecure-hash-function
    "N801", #invalid-class-name
    "ANN202", #missing-return-type-private-function
    "ANN206", #missing-return-type-class-method
    "PLR0913", #too-many-arguments
    "PLR0917", #too-many-positional-arguments
    "ANN401", #any-type

]
